### PR TITLE
fix: Allow selecting second image in a paragraph

### LINKED ISSUE #349: Image toolbar positioning
**To Reproduce**
1. Paste an image
2. Paste another image right next to it (they must be in the same paragraph)
3. Select second image
4. Toolbar appears above first image

**Expected behavior**

Should appear on the correct image

**Version**

v11.1.0

### PR DESCRIPTION
**Pull request by tommoor**
fix: More predictable behavior when center-aligning image

closes #349

### CODE REVIEW

File: src/components/FloatingToolbar.tsx [hunk 1]
```diff
@@ -86,7 +86,7 @@ function usePosition({ menuRef, isSelectingText, props }) {
     selection.node && selection.node.type.name === "image";
   // Images need their own positioning to get the toolbar in the center
   if (isImageSelection) {
-    const { node: element } = view.domAtPos(selection.from);
+    const element = view.nodeDOM(selection.from);
```
Comment (tommoor) [inline src/components/FloatingToolbar.tsx:89]: This was the key to selecting the correct dom element
